
find_package(FLTK)
include(FindPackageHandleStandardArgs)
include(StaticLinking)

if(NOT FLTK_FOUND)
  set(StaticFLTK_FOUND "StaticFLTK-NOTFOUND")
else()
  find_static_library_of_shared_library(StaticFLTK_BASE_LIBRARY "${FLTK_BASE_LIBRARY}")
  if(NOT StaticFLTK_BASE_LIBRARY)
    set(StaticFLTK_FOUND "StaticFLTK-NOTFOUND")
  else()
    set(StaticFLTK_FOUND "StaticFLTK-FOUND")
    message(STATUS "Found static FLTK: ${StaticFLTK_BASE_LIBRARY}")
    if(NOT FLTK_SKIP_OPENGL)
      find_static_library_of_shared_library(StaticFLTK_GL_LIBRARY "${FLTK_GL_LIBRARY}")
      message(STATUS "Found static FLTK GL: ${StaticFLTK_GL_LIBRARY}")
    endif()
    if(NOT FLTK_SKIP_FORMS)
      find_static_library_of_shared_library(StaticFLTK_FORMS_LIBRARY "${FLTK_FORMS_LIBRARY}")
      message(STATUS "Found static FLTK forms: ${StaticFLTK_FORMS_LIBRARY}")
    endif()
    if(NOT FLTK_SKIP_IMAGES)
      find_static_library_of_shared_library(StaticFLTK_IMAGES_LIBRARY "${FLTK_IMAGES_LIBRARY}")
      message(STATUS "Found static FLTK images: ${StaticFLTK_IMAGES_LIBRARY}")
     endif()
  endif()
  set(StaticFLTK_LIBRARIES)
  foreach(_lib ${FLTK_LIBRARIES})
    if(_lib STREQUAL "${FLTK_BASE_LIBRARY}")
      list(APPEND StaticFLTK_LIBRARIES "${StaticFLTK_BASE_LIBRARY}")
    elseif(_lib STREQUAL "${FLTK_GL_LIBRARY}")
      list(APPEND StaticFLTK_LIBRARIES "${StaticFLTK_GL_LIBRARY}")
    elseif(_lib STREQUAL "${FLTK_FORMS_LIBRARY}")
      list(APPEND StaticFLTK_LIBRARIES "${StaticFLTK_FORMS_LIBRARY}")
    elseif(_lib STREQUAL "${FLTK_IMAGES_LIBRARY}")
      list(APPEND StaticFLTK_LIBRARIES "${StaticFLTK_IMAGES_LIBRARY}")
    else()
      list(APPEND StaticFLTK_LIBRARIES "${_lib}")
    endif()
  endforeach()
endif()

find_package_handle_standard_args(StaticFLTK
  REQUIRED_VARS StaticFLTK_FOUND)
