
macro(require_path VAR NAME1)
  find_path(${VAR} "${NAME1}" ${ARGN})
  if(NOT ${VAR})
    message(FATAL_ERROR "cannot find path of ${NAME1}")
  else()
    message(STATUS "Found ${NAME1} in path: ${${VAR}}")
  endif()
endmacro()

macro(require_file VAR NAME1)
  find_file(${VAR} "${NAME1}" ${ARGN})
  if(NOT ${VAR})
    message(FATAL_ERROR "cannot find file ${NAME1}")
  else()
    message(STATUS "Found file ${NAME1}: ${${VAR}}")
  endif()
endmacro()

macro(require_library VAR NAME1)
  find_library(${VAR} "${NAME1}" ${ARGN})
  if(NOT ${VAR})
    message(FATAL_ERROR "cannot find library ${NAME1}")
  else()
    message(STATUS "Found library ${NAME1}: ${${VAR}}")
  endif()
endmacro()

macro(require_static_library VAR NAME1)
  find_static_library(${VAR} "${NAME1}" ${ARGN})
  if(NOT ${VAR})
    message(FATAL_ERROR "cannot find static library ${NAME1}")
  else()
    message(STATUS "Found static library ${NAME1}: ${${VAR}}")
  endif()
endmacro()
